// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Repositories.Migrations
{
    [DbContext(typeof(BackEndContext))]
    [Migration("20260316022703_DefaultValueAtivo")]
    partial class DefaultValueAtivo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("BackEnd.Dominio.Entidades.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateOnly>("DataCriada")
                        .HasColumnType("date")
                        .HasColumnName("DataCriada");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Descricao");

                    b.Property<DateOnly>("Prazo")
                        .HasColumnType("date")
                        .HasColumnName("Prazo");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Prioridade");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Tarefas", (string)null);
                });

            modelBuilder.Entity("BackEnd.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Ativo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Email");

                    b.Property<int>("Funcao")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Funcao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("SenhaHash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("BackEnd.Dominio.Entidades.UsuarioTarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DataAtribuicao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateOnly(2026, 3, 15));

                    b.Property<int>("TarefaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TarefaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuariosTarefas", (string)null);
                });

            modelBuilder.Entity("BackEnd.Dominio.Entidades.UsuarioTarefa", b =>
                {
                    b.HasOne("BackEnd.Dominio.Entidades.Tarefa", "Tarefa")
                        .WithMany("UsuariosTarefa")
                        .HasForeignKey("TarefaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackEnd.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("UsuarioTarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarefa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BackEnd.Dominio.Entidades.Tarefa", b =>
                {
                    b.Navigation("UsuariosTarefa");
                });

            modelBuilder.Entity("BackEnd.Dominio.Entidades.Usuario", b =>
                {
                    b.Navigation("UsuarioTarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
